### PR TITLE
Adding DataFrames output to SeisHeaderInfo

### PR DESCRIPTION
**Pull request by AtilaSaraiva**
This PR returns the information gathered by SeisHeaderInfo to a DataFrame, a spreadsheet-like data format. This can help the user have the information used in the script.

I also made a few formating changes to the function.

### CODE REVIEW

**Comment by msacchi** [comment]
nice feature if you can produce a nice organize table of headers to qc imput data.-:)

**Comment by AtilaSaraiva** [comment]
Hey Mauricio, thx for the review!

Do you mean a table with the full header instead of just the mean, max and min in a table? If you want I can create a function that transforms the header into a table or we can make it the default.

**Comment by msacchi** [comment]
Some summary as min/max mean is sufficient like SU does with surange.

**Comment by AtilaSaraiva** [comment]
in that case this is what the code is doing! It returns a table with type DataFrame

image

**Pull request merged**
